// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	projectv1 "github.com/openshift/api/project/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProjectRequestLimits implements ProjectRequestLimitInterface
type FakeProjectRequestLimits struct {
	Fake *FakeProjectV1
}

var projectrequestlimitsResource = schema.GroupVersionResource{Group: "project.openshift.io", Version: "v1", Resource: "projectrequestlimits"}

var projectrequestlimitsKind = schema.GroupVersionKind{Group: "project.openshift.io", Version: "v1", Kind: "ProjectRequestLimit"}

// Get takes name of the projectRequestLimit, and returns the corresponding projectRequestLimit object, and an error if there is any.
func (c *FakeProjectRequestLimits) Get(ctx context.Context, name string, options v1.GetOptions) (result *projectv1.ProjectRequestLimit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(projectrequestlimitsResource, name), &projectv1.ProjectRequestLimit{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectv1.ProjectRequestLimit), err
}

// List takes label and field selectors, and returns the list of ProjectRequestLimits that match those selectors.
func (c *FakeProjectRequestLimits) List(ctx context.Context, opts v1.ListOptions) (result *projectv1.ProjectRequestLimitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(projectrequestlimitsResource, projectrequestlimitsKind, opts), &projectv1.ProjectRequestLimitList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &projectv1.ProjectRequestLimitList{ListMeta: obj.(*projectv1.ProjectRequestLimitList).ListMeta}
	for _, item := range obj.(*projectv1.ProjectRequestLimitList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectRequestLimits.
func (c *FakeProjectRequestLimits) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(projectrequestlimitsResource, opts))
}

// Create takes the representation of a projectRequestLimit and creates it.  Returns the server's representation of the projectRequestLimit, and an error, if there is any.
func (c *FakeProjectRequestLimits) Create(ctx context.Context, projectRequestLimit *projectv1.ProjectRequestLimit, opts v1.CreateOptions) (result *projectv1.ProjectRequestLimit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(projectrequestlimitsResource, projectRequestLimit), &projectv1.ProjectRequestLimit{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectv1.ProjectRequestLimit), err
}

// Update takes the representation of a projectRequestLimit and updates it. Returns the server's representation of the projectRequestLimit, and an error, if there is any.
func (c *FakeProjectRequestLimits) Update(ctx context.Context, projectRequestLimit *projectv1.ProjectRequestLimit, opts v1.UpdateOptions) (result *projectv1.ProjectRequestLimit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(projectrequestlimitsResource, projectRequestLimit), &projectv1.ProjectRequestLimit{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectv1.ProjectRequestLimit), err
}

// Delete takes name of the projectRequestLimit and deletes it. Returns an error if one occurs.
func (c *FakeProjectRequestLimits) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(projectrequestlimitsResource, name, opts), &projectv1.ProjectRequestLimit{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectRequestLimits) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(projectrequestlimitsResource, listOpts)

	_, err := c.Fake.Invokes(action, &projectv1.ProjectRequestLimitList{})
	return err
}

// Patch applies the patch and returns the patched projectRequestLimit.
func (c *FakeProjectRequestLimits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *projectv1.ProjectRequestLimit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(projectrequestlimitsResource, name, pt, data, subresources...), &projectv1.ProjectRequestLimit{})
	if obj == nil {
		return nil, err
	}
	return obj.(*projectv1.ProjectRequestLimit), err
}
